INSERT INTO ESTADOS_HOMOLOGADOS_CONFE(ESTADO_CONFE,CODIGO) VALUES
	('CANCELADA',2),
	('DEVUELTA',1),
	('EN MORA',1),
	('PAGADA',3),
	('RECUPERADA POR VENTA FONSA',3),
	('RECUPERADA TOTAL',3),
	('RECUPERADO TOTAL',3),
	('VIGENTE',1),
	('VIGENTE - REFINANCIACION',1),
	('RADICADA',1),
	('PRORROGA',1)

INSERT INTO ESTADOS_HOMOLOGADOS_FONDO(ESTADO_BANCO,CODIGO) VALUES 
('VIGENTE',1),
('CANCELADA',2),
('CANCELADAS POR NOVACION DE CARTERA',2),
('GARANTIA PAGADA - FGC',3),
('RECUPERADA',3),
('CANCELADO',2)